import React from 'react';

function Privacy() {
  return (
    <div className="container">
      <div className="privacy-wrapper">
        <h1 className="privacy-title">Privacy Policy</h1>
        <p className="privacy-date">Last updated: January 16, 2025</p>
        
        <div className="privacy-content">
          <p>This Privacy Policy outlines our practices and procedures regarding the collection, use, and disclosure of your information when you use our service. It also explains your privacy rights and how the law protects you.</p>
          
          <p>We utilize your personal data to provide and enhance the service. By using the service, you agree to the collection and use of information in accordance with this Privacy Policy.</p>
          
          <h2>Interpretation and Definitions</h2>
          
          <h3>Interpretation</h3>
          <p>Terms with capitalized initials have defined meanings specified under certain conditions. These definitions hold the same meaning regardless of whether they are singular or plural.</p>
          
          <h3>Definitions</h3>
          <p>For the purposes of this Privacy Policy:</p>
          <ul>
            <li><strong>Business</strong> refers to the legal entity, InstaSave, that collects consumers' personal information and determines the purposes and means of the processing of such information.</li>
            <li><strong>Company</strong> refers to InstaSave, located in the United States, Alaska, and may be referred to as "We," "Us," or "Our" in this Policy. The Company is the Data Controller under the GDPR.</li>
            <li><strong>Consumer</strong> refers to a natural person who is a resident of California and is the subject of personal information collected by the Company.</li>
            <li><strong>Cookies</strong> are small files containing browsing history details that are placed on your device by a website.</li>
            <li><strong>Country</strong> refers to Alaska, United States.</li>
            <li><strong>Data Controller</strong> refers to the Company as the legal entity that determines the purposes and means of processing personal data.</li>
            <li><strong>Device</strong> means any device, such as a computer, cellphone, or tablet, that can access the service.</li>
            <li><strong>Do Not Track (DNT)</strong> is a concept promoted by US regulatory authorities for allowing users to control online tracking.</li>
            <li><strong>Personal Data</strong> refers to any information related to an identified or identifiable individual. It includes various types of information as defined under GDPR and CCPA.</li>
            <li><strong>Sale</strong> refers to the transfer of a consumer's personal information to another business or third party for valuable consideration.</li>
            <li><strong>Service</strong> refers to the website, InstaSave.</li>
            <li><strong>Service Provider</strong> refers to third-party companies or individuals employed by the Company to facilitate and provide the Service, as well as analyze its usage.</li>
            <li><strong>Third-party Social Media Service</strong> refers to any website or social network through which users can log in or create accounts to use the Service.</li>
            <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
            <li><strong>Website</strong> refers to InstaSave, accessible from https://instasave.world</li>
            <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable. Under GDPR, You can be referred to as the Data Subject or as the User.</li>
          </ul>

          <h2>Collecting and Using Your Personal Data</h2>

          <h3>Types of Data Collected</h3>

          <h4>Personal Data</h4>
          <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
          <ul>
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Usage Data</li>
          </ul>

          <h4>Usage Data</h4>
          <p>Usage Data is collected automatically when using the Service.</p>
          <p>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
          <p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>

          <h3>Tracking Technologies and Cookies</h3>
          <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.</p>
          <p>You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.</p>
          <p>Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close your web browser.</p>
          <p>We use both Session and Persistent Cookies for the purposes set out below:</p>
          <ul>
            <li><strong>Necessary / Essential Cookies</strong>
              <ul>
                <li>Type: Session Cookies</li>
                <li>Administered by: Us</li>
                <li>Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features.</li>
              </ul>
            </li>
            <li><strong>Functionality Cookies</strong>
              <ul>
                <li>Type: Persistent Cookies</li>
                <li>Administered by: Us</li>
                <li>Purpose: These Cookies allow us to remember choices You make when You use the Website.</li>
              </ul>
            </li>
            <li><strong>Tracking and Performance Cookies</strong>
              <ul>
                <li>Type: Persistent Cookies</li>
                <li>Administered by: Third-Parties</li>
                <li>Purpose: These Cookies are used to track information about traffic to the Website and how users use the Website.</li>
              </ul>
            </li>
          </ul>

          <h3>Use of Your Personal Data</h3>
          <p>The Company may use Personal Data for the following purposes:</p>
          <ul>
            <li>To provide and maintain our Service</li>
            <li>To notify you about changes to our Service</li>
            <li>To provide customer support</li>
            <li>To provide analysis or valuable information so that we can improve the Service</li>
            <li>To monitor the usage of the Service</li>
            <li>To detect, prevent and address technical issues</li>
          </ul>

          <h3>Data Retention and Transfer</h3>
          <p>We retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.</p>
          <p>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. This means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ from those in Your jurisdiction.</p>

          <h3>Security of Your Personal Data</h3>
          <p>The security of Your Personal Data is important to us but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>

          <h2>GDPR Privacy Rights</h2>
          <p>If you are a resident of the European Economic Area (EEA), you have certain data protection rights. The Company aims to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.</p>
          <p>Your rights under GDPR include:</p>
          <ul>
            <li>The right to access, update or delete your Personal Data</li>
            <li>The right of rectification</li>
            <li>The right to object to processing</li>
            <li>The right of restriction</li>
            <li>The right to data portability</li>
            <li>The right to withdraw consent</li>
          </ul>

          <h2>CCPA Privacy Rights</h2>
          <p>Under CCPA, California residents have specific rights regarding their personal information:</p>
          <ul>
            <li>The right to notice</li>
            <li>The right to access</li>
            <li>The right to opt-out of the sale of personal information</li>
            <li>The right to request deletion</li>
            <li>The right to non-discrimination</li>
          </ul>

          <h2>Do Not Sell My Personal Information</h2>
          <p>We do not sell personal information. However, the Service Providers we partner with may use technology on the Service that qualifies as a "sale" under CCPA.</p>

          <h2>Changes to this Privacy Policy</h2>
          <p>We may update our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page and updating the "Last updated" date.</p>
          <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>

          <h2>Contact Us</h2>
          <p>If you have any questions about this Privacy Policy, You can contact us:</p>
          <ul>
            <li>By email: <a href="mailto:contact@instasave.world">contact@instasave.world</a></li>
            <li>By visiting this page on our website: <a href="https://instasave.world/contact-us">https://instasave.world/contact-us</a></li>
          </ul>
        </div>
      </div>
    </div>
  );
}

export default Privacy; 